### ISSUE TITLE
[Bug]: Fresh react-app with dojo-starter not working for me with Dojo 0.4.2

### ISSUE THREAD

**Issue by willemolding** [dojoengine/dojo.js#95] opened 2023-12-22 04:52 UTC
### Dojo.js Version

0.2.9

### What happened?

Having trouble getting the basic react-app template working with the latest dojo stack

```
╰─➤  torii --version
torii 0.4.2
╰─➤  sozo --version
sozo 0.4.2
╰─➤  katana --version
katana 0.4.2
```

In Firefox: react-app displays nothing. Network tab shows GET request to torii `0.0.0.0:8080/world.World/SubscribeModels` is stuck pending

In Chrome: react-app UI components are displayed. Network tab still shows same request stuck pending. Can create burner wallets but dojo functionality failes with:

```
uncaught (in promise) Error: Error fetching transaction receipt
    at @dojoengine_create-burner.js?v=eb920faa:27739:15
```

### What is the expected behavior?

Fresh react-app should work the same on common brower types without issue

## Setup project

- `npx @dojoengine/create-dojo`

## terminal 1
- `cd dojo-starter && katana --disable-fee`

## terminal 2
- `cd dojo-starter && sozo build && sozo migrate`
- `torii --world 0x33ac2f528bb97cc7b79148fd1756dc368be0e95d391d8c6d6473ecb60b4560e`
    - world address from output of migrate command
    - can see that this registers models Moves and Position

## terminal 3
- `cd react-app`
- Change `VITE_PUBLIC_WORLD_ADDRESS` in `.env` to same as above
- `bun install && bun run dev`

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by ponderingdemocritus** [comment] 2023-12-23 21:09
This error is from the burner - you can ignore it, it shouldn't break syncing.

This will be fixed shortly

**Comment by ponderingdemocritus** [comment] 2024-01-16 22:53
duplicate of #89

**Closed by ponderingdemocritus** 2024-01-16 22:53 UTC
Labels: bug
